name: Build hospital service

on: [workflow_dispatch]

jobs:
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v2
    
      - name: Hospital service build
        uses: ballerina-platform/ballerina-action@2201.7.2
        with:
          args: 
            build

      - name: Upload JAR
        uses: actions/upload-artifact@v2
        with:
          name: hospitalservice.jar
          path: ./hospitalservice/target/bin/
